//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiReD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruitment
    {
        public int id { get; set; }
        public string Department { get; set; }
        public string Post { get; set; }
        public string Status { get; set; }
        public Nullable<int> Info { get; set; }
    
        public virtual Interview Interview { get; set; }
    }
}
